ivohf:
  vars:
    ansible_ssh_user: "{{ lookup('env', 'USER') }}"
    ansible_ssh_private_key_file: ~/.ssh/id_ivocap
    ansible_python_interpreter: /usr/bin/python3
    ansible_become_password: '{{ servers_become_pass }}'

  hosts:
    poisson:
      ansible_host: "{{ lookup('env', 'POISSON_IP') }}"
      ansible_port: 66
      ansible_become_password: '{{ poisson_become_pass }}'
    "4":
      ansible_host: 192.168.47.4
    "5":
      ansible_host: 192.168.47.5
    "6":
      ansible_host: 192.168.47.6
    "8":
      ansible_host: 192.168.47.8
    "9":
      ansible_host: 192.168.47.9
    "10":
      ansible_host: 192.168.47.10
    "11":
      ansible_host: 192.168.47.11
    "13":
      ansible_host: 192.168.47.13
    "14":
      ansible_host: 192.168.47.14
    "18":
      ansible_host: 192.168.47.18
    "50":
      ansible_host: 192.168.47.50
    "52":
      ansible_host: 192.168.50.52
    "206":
      ansible_host: 192.168.50.206
    "207":
      ansible_host: 192.168.47.207
    "112":
      ansible_host: 192.168.47.112
    "113":
      ansible_host: 192.168.47.113
    "114":
      ansible_host: 192.168.47.114
    "115":
      ansible_host: 192.168.47.115
